AllCops:
  Exclude:
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Metrics/MethodLength:
  Max: 15
