version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rails-web-server
    ports:
      - 5439:5432
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis
    restart: always
    ports:
      - 6399:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
