development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:admin@localhost:6399/1" } %>

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:admin@localhost:6399/1" } %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:admin@localhost:6399/1" } %>
  channel_prefix: simple_web_server_production
