name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.150.0
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: bundle install

      - name: Run static analyzer
        run: brakeman && rubocop
